# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import coordinator_commands_pb2 as coordinator__commands__pb2
except ImportError:
    from infrastructure import coordinator_commands_pb2 as coordinator__commands__pb2


GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_commands_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorCommandServiceStub:
    """gRPC service exposed by the .NET Coordinator for Trainer command streams.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeCommands = channel.unary_stream(
                '/trainswarm.coordinator.CoordinatorCommandService/SubscribeCommands',
                request_serializer=coordinator__commands__pb2.TrainerRegistrationRequest.SerializeToString,
                response_deserializer=coordinator__commands__pb2.CommandEnvelope.FromString,
                _registered_method=True)


class CoordinatorCommandServiceServicer:
    """gRPC service exposed by the .NET Coordinator for Trainer command streams.
    """

    def SubscribeCommands(self, request, context):
        """Initiates a long-lived server-to-client command streaming session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorCommandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCommands,
                    request_deserializer=coordinator__commands__pb2.TrainerRegistrationRequest.FromString,
                    response_serializer=coordinator__commands__pb2.CommandEnvelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trainswarm.coordinator.CoordinatorCommandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trainswarm.coordinator.CoordinatorCommandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorCommandService:
    """gRPC service exposed by the .NET Coordinator for Trainer command streams.
    """

    @staticmethod
    def SubscribeCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trainswarm.coordinator.CoordinatorCommandService/SubscribeCommands',
            coordinator__commands__pb2.TrainerRegistrationRequest.SerializeToString,
            coordinator__commands__pb2.CommandEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
