<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\coordinator_commands.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TrainSwarm.Coordinator.Domain\TrainSwarm.Coordinator.Domain.csproj" />
    </ItemGroup>

</Project>
