// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: p2p.proto

package p2pv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reachability int32

const (
	Reachability_REACHABILITY_UNKNOWN    Reachability = 0
	Reachability_REACHABILITY_PUBLIC     Reachability = 1
	Reachability_REACHABILITY_PRIVATE    Reachability = 2
	Reachability_REACHABILITY_RELAY_ONLY Reachability = 3
)

// Enum value maps for Reachability.
var (
	Reachability_name = map[int32]string{
		0: "REACHABILITY_UNKNOWN",
		1: "REACHABILITY_PUBLIC",
		2: "REACHABILITY_PRIVATE",
		3: "REACHABILITY_RELAY_ONLY",
	}
	Reachability_value = map[string]int32{
		"REACHABILITY_UNKNOWN":    0,
		"REACHABILITY_PUBLIC":     1,
		"REACHABILITY_PRIVATE":    2,
		"REACHABILITY_RELAY_ONLY": 3,
	}
)

func (x Reachability) Enum() *Reachability {
	p := new(Reachability)
	*p = x
	return p
}

func (x Reachability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reachability) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_enumTypes[0].Descriptor()
}

func (Reachability) Type() protoreflect.EnumType {
	return &file_p2p_proto_enumTypes[0]
}

func (x Reachability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reachability.Descriptor instead.
func (Reachability) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

type ConnectionState int32

const (
	ConnectionState_STATE_DISCONNECTED     ConnectionState = 0
	ConnectionState_STATE_CONNECTING       ConnectionState = 1
	ConnectionState_STATE_RELAY_CONNECTED  ConnectionState = 2
	ConnectionState_STATE_PUNCHING         ConnectionState = 3
	ConnectionState_STATE_DIRECT_CONNECTED ConnectionState = 4
	ConnectionState_STATE_FAILED           ConnectionState = 5
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "STATE_DISCONNECTED",
		1: "STATE_CONNECTING",
		2: "STATE_RELAY_CONNECTED",
		3: "STATE_PUNCHING",
		4: "STATE_DIRECT_CONNECTED",
		5: "STATE_FAILED",
	}
	ConnectionState_value = map[string]int32{
		"STATE_DISCONNECTED":     0,
		"STATE_CONNECTING":       1,
		"STATE_RELAY_CONNECTED":  2,
		"STATE_PUNCHING":         3,
		"STATE_DIRECT_CONNECTED": 4,
		"STATE_FAILED":           5,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_enumTypes[1].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_p2p_proto_enumTypes[1]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_UNKNOWN                       EventType = 0
	EventType_EVENT_PEER_CONNECTED                EventType = 1
	EventType_EVENT_PEER_DISCONNECTED             EventType = 2
	EventType_EVENT_CONNECTION_UPGRADED_TO_DIRECT EventType = 3
	EventType_EVENT_HOLE_PUNCH_FAILED             EventType = 4
	EventType_EVENT_TRANSFER_REQUESTED            EventType = 5
	EventType_EVENT_TRANSFER_STARTED              EventType = 6
	EventType_EVENT_TRANSFER_PROGRESS             EventType = 7
	EventType_EVENT_TRANSFER_COMPLETED            EventType = 8
	EventType_EVENT_TRANSFER_FAILED               EventType = 9
	EventType_EVENT_TRANSFER_CANCELLED            EventType = 10
	EventType_EVENT_FILE_REQUESTED                EventType = 11
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_UNKNOWN",
		1:  "EVENT_PEER_CONNECTED",
		2:  "EVENT_PEER_DISCONNECTED",
		3:  "EVENT_CONNECTION_UPGRADED_TO_DIRECT",
		4:  "EVENT_HOLE_PUNCH_FAILED",
		5:  "EVENT_TRANSFER_REQUESTED",
		6:  "EVENT_TRANSFER_STARTED",
		7:  "EVENT_TRANSFER_PROGRESS",
		8:  "EVENT_TRANSFER_COMPLETED",
		9:  "EVENT_TRANSFER_FAILED",
		10: "EVENT_TRANSFER_CANCELLED",
		11: "EVENT_FILE_REQUESTED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN":                       0,
		"EVENT_PEER_CONNECTED":                1,
		"EVENT_PEER_DISCONNECTED":             2,
		"EVENT_CONNECTION_UPGRADED_TO_DIRECT": 3,
		"EVENT_HOLE_PUNCH_FAILED":             4,
		"EVENT_TRANSFER_REQUESTED":            5,
		"EVENT_TRANSFER_STARTED":              6,
		"EVENT_TRANSFER_PROGRESS":             7,
		"EVENT_TRANSFER_COMPLETED":            8,
		"EVENT_TRANSFER_FAILED":               9,
		"EVENT_TRANSFER_CANCELLED":            10,
		"EVENT_FILE_REQUESTED":                11,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_p2p_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{2}
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{0}
}

type GetNodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ListenAddresses []string               `protobuf:"bytes,2,rep,name=listen_addresses,json=listenAddresses,proto3" json:"listen_addresses,omitempty"`
	RelayAddresses  []string               `protobuf:"bytes,3,rep,name=relay_addresses,json=relayAddresses,proto3" json:"relay_addresses,omitempty"`
	Reachability    Reachability           `protobuf:"varint,4,opt,name=reachability,proto3,enum=p2p.v1.Reachability" json:"reachability,omitempty"`
	GrpcApiVersion  string                 `protobuf:"bytes,5,opt,name=grpc_api_version,json=grpcApiVersion,proto3" json:"grpc_api_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeInfoResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetListenAddresses() []string {
	if x != nil {
		return x.ListenAddresses
	}
	return nil
}

func (x *GetNodeInfoResponse) GetRelayAddresses() []string {
	if x != nil {
		return x.RelayAddresses
	}
	return nil
}

func (x *GetNodeInfoResponse) GetReachability() Reachability {
	if x != nil {
		return x.Reachability
	}
	return Reachability_REACHABILITY_UNKNOWN
}

func (x *GetNodeInfoResponse) GetGrpcApiVersion() string {
	if x != nil {
		return x.GrpcApiVersion
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Multiaddrs    []string               `protobuf:"bytes,2,rep,name=multiaddrs,proto3" json:"multiaddrs,omitempty"` // Can be direct or relay circuit multiaddrs
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ConnectRequest) GetMultiaddrs() []string {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

func (x *ConnectRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	State         ConnectionState        `protobuf:"varint,3,opt,name=state,proto3,enum=p2p.v1.ConnectionState" json:"state,omitempty"`
	Transport     string                 `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	Direct        bool                   `protobuf:"varint,5,opt,name=direct,proto3" json:"direct,omitempty"`
	RelayAddress  string                 `protobuf:"bytes,6,opt,name=relay_address,json=relayAddress,proto3" json:"relay_address,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ConnectResponse) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_STATE_DISCONNECTED
}

func (x *ConnectResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConnectResponse) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *ConnectResponse) GetRelayAddress() string {
	if x != nil {
		return x.RelayAddress
	}
	return ""
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetConnectionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionStatusRequest) Reset() {
	*x = GetConnectionStatusRequest{}
	mi := &file_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusRequest) ProtoMessage() {}

func (x *GetConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *GetConnectionStatusRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type GetConnectionStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	State           ConnectionState        `protobuf:"varint,3,opt,name=state,proto3,enum=p2p.v1.ConnectionState" json:"state,omitempty"`
	Direct          bool                   `protobuf:"varint,4,opt,name=direct,proto3" json:"direct,omitempty"`
	Transport       string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	RemoteAddresses []string               `protobuf:"bytes,6,rep,name=remote_addresses,json=remoteAddresses,proto3" json:"remote_addresses,omitempty"`
	ConnectedAt     int64                  `protobuf:"varint,7,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`    // Unix timestamp
	LastActivity    int64                  `protobuf:"varint,8,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"` // Unix timestamp
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetConnectionStatusResponse) Reset() {
	*x = GetConnectionStatusResponse{}
	mi := &file_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusResponse) ProtoMessage() {}

func (x *GetConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *GetConnectionStatusResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GetConnectionStatusResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetConnectionStatusResponse) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_STATE_DISCONNECTED
}

func (x *GetConnectionStatusResponse) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *GetConnectionStatusResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *GetConnectionStatusResponse) GetRemoteAddresses() []string {
	if x != nil {
		return x.RemoteAddresses
	}
	return nil
}

func (x *GetConnectionStatusResponse) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *GetConnectionStatusResponse) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_p2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{8}
}

type NodeEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=p2p.v1.EventType" json:"type,omitempty"`
	PeerId     string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TransferId string                 `protobuf:"bytes,3,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Message    string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Used only when type == EVENT_TRANSFER_REQUESTED
	Metadata      *TransferMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_p2p_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{9}
}

func (x *NodeEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNKNOWN
}

func (x *NodeEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NodeEvent) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *NodeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeEvent) GetMetadata() *TransferMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TransferMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMetadata) Reset() {
	*x = TransferMetadata{}
	mi := &file_p2p_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMetadata) ProtoMessage() {}

func (x *TransferMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMetadata.ProtoReflect.Descriptor instead.
func (*TransferMetadata) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{10}
}

func (x *TransferMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TransferMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *TransferMetadata) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SourcePath    string                 `protobuf:"bytes,6,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Overwrite     bool                   `protobuf:"varint,7,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_p2p_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{11}
}

func (x *SendFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *SendFileRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SendFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SendFileRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *SendFileRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *SendFileRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type AcceptFileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	Overwrite       bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptFileRequest) Reset() {
	*x = AcceptFileRequest{}
	mi := &file_p2p_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFileRequest) ProtoMessage() {}

func (x *AcceptFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFileRequest.ProtoReflect.Descriptor instead.
func (*AcceptFileRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptFileRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *AcceptFileRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *AcceptFileRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type TransferEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	State            EventType              `protobuf:"varint,2,opt,name=state,proto3,enum=p2p.v1.EventType" json:"state,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	SpeedBps         int64                  `protobuf:"varint,5,opt,name=speed_bps,json=speedBps,proto3" json:"speed_bps,omitempty"`
	Progress         float32                `protobuf:"fixed32,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferEvent) Reset() {
	*x = TransferEvent{}
	mi := &file_p2p_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvent) ProtoMessage() {}

func (x *TransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvent.ProtoReflect.Descriptor instead.
func (*TransferEvent) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{13}
}

func (x *TransferEvent) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferEvent) GetState() EventType {
	if x != nil {
		return x.State
	}
	return EventType_EVENT_UNKNOWN
}

func (x *TransferEvent) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *TransferEvent) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferEvent) GetSpeedBps() int64 {
	if x != nil {
		return x.SpeedBps
	}
	return 0
}

func (x *TransferEvent) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TransferEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferRequest) Reset() {
	*x = CancelTransferRequest{}
	mi := &file_p2p_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferRequest) ProtoMessage() {}

func (x *CancelTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelTransferRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type CancelTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferResponse) Reset() {
	*x = CancelTransferResponse{}
	mi := &file_p2p_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferResponse) ProtoMessage() {}

func (x *CancelTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelTransferResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferStatusRequest) Reset() {
	*x = GetTransferStatusRequest{}
	mi := &file_p2p_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferStatusRequest) ProtoMessage() {}

func (x *GetTransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransferStatusRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type TransferStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	State            EventType              `protobuf:"varint,2,opt,name=state,proto3,enum=p2p.v1.EventType" json:"state,omitempty"`
	BytesTransferred int64                  `protobuf:"varint,3,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferStatusResponse) Reset() {
	*x = TransferStatusResponse{}
	mi := &file_p2p_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusResponse) ProtoMessage() {}

func (x *TransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusResponse.ProtoReflect.Descriptor instead.
func (*TransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{17}
}

func (x *TransferStatusResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferStatusResponse) GetState() EventType {
	if x != nil {
		return x.State
	}
	return EventType_EVENT_UNKNOWN
}

func (x *TransferStatusResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *TransferStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type RequestFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFileRequest) Reset() {
	*x = RequestFileRequest{}
	mi := &file_p2p_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFileRequest) ProtoMessage() {}

func (x *RequestFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFileRequest.ProtoReflect.Descriptor instead.
func (*RequestFileRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{18}
}

func (x *RequestFileRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RequestFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type RequestFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFileResponse) Reset() {
	*x = RequestFileResponse{}
	mi := &file_p2p_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFileResponse) ProtoMessage() {}

func (x *RequestFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFileResponse.ProtoReflect.Descriptor instead.
func (*RequestFileResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rawDescGZIP(), []int{19}
}

func (x *RequestFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_p2p_proto protoreflect.FileDescriptor

const file_p2p_proto_rawDesc = "" +
	"\n" +
	"\tp2p.proto\x12\x06p2p.v1\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xe6\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12)\n" +
	"\x10listen_addresses\x18\x02 \x03(\tR\x0flistenAddresses\x12'\n" +
	"\x0frelay_addresses\x18\x03 \x03(\tR\x0erelayAddresses\x128\n" +
	"\freachability\x18\x04 \x01(\x0e2\x14.p2p.v1.ReachabilityR\freachability\x12(\n" +
	"\x10grpc_api_version\x18\x05 \x01(\tR\x0egrpcApiVersion\"h\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1e\n" +
	"\n" +
	"multiaddrs\x18\x02 \x03(\tR\n" +
	"multiaddrs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"\xef\x01\n" +
	"\x0fConnectResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.p2p.v1.ConnectionStateR\x05state\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransport\x12\x16\n" +
	"\x06direct\x18\x05 \x01(\bR\x06direct\x12#\n" +
	"\rrelay_address\x18\x06 \x01(\tR\frelayAddress\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\",\n" +
	"\x11DisconnectRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aGetConnectionStatusRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\xb3\x02\n" +
	"\x1bGetConnectionStatusResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12-\n" +
	"\x05state\x18\x03 \x01(\x0e2\x17.p2p.v1.ConnectionStateR\x05state\x12\x16\n" +
	"\x06direct\x18\x04 \x01(\bR\x06direct\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12)\n" +
	"\x10remote_addresses\x18\x06 \x03(\tR\x0fremoteAddresses\x12!\n" +
	"\fconnected_at\x18\a \x01(\x03R\vconnectedAt\x12#\n" +
	"\rlast_activity\x18\b \x01(\x03R\flastActivity\"\x14\n" +
	"\x12WatchEventsRequest\"\xbc\x01\n" +
	"\tNodeEvent\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.p2p.v1.EventTypeR\x04type\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1f\n" +
	"\vtransfer_id\x18\x03 \x01(\tR\n" +
	"transferId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x124\n" +
	"\bmetadata\x18\x05 \x01(\v2\x18.p2p.v1.TransferMetadataR\bmetadata\"d\n" +
	"\x10TransferMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"\xdc\x01\n" +
	"\x0fSendFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x1f\n" +
	"\vsource_path\x18\x06 \x01(\tR\n" +
	"sourcePath\x12\x1c\n" +
	"\toverwrite\x18\a \x01(\bR\toverwrite\"}\n" +
	"\x11AcceptFileRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\"\xf6\x01\n" +
	"\rTransferEvent\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.p2p.v1.EventTypeR\x05state\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x1b\n" +
	"\tspeed_bps\x18\x05 \x01(\x03R\bspeedBps\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x02R\bprogress\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"8\n" +
	"\x15CancelTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"2\n" +
	"\x16CancelTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x18GetTransferStatusRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\xb0\x01\n" +
	"\x16TransferStatusResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.p2p.v1.EventTypeR\x05state\x12+\n" +
	"\x11bytes_transferred\x18\x03 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\"J\n" +
	"\x12RequestFileRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"/\n" +
	"\x13RequestFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*x\n" +
	"\fReachability\x12\x18\n" +
	"\x14REACHABILITY_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13REACHABILITY_PUBLIC\x10\x01\x12\x18\n" +
	"\x14REACHABILITY_PRIVATE\x10\x02\x12\x1b\n" +
	"\x17REACHABILITY_RELAY_ONLY\x10\x03*\x9c\x01\n" +
	"\x0fConnectionState\x12\x16\n" +
	"\x12STATE_DISCONNECTED\x10\x00\x12\x14\n" +
	"\x10STATE_CONNECTING\x10\x01\x12\x19\n" +
	"\x15STATE_RELAY_CONNECTED\x10\x02\x12\x12\n" +
	"\x0eSTATE_PUNCHING\x10\x03\x12\x1a\n" +
	"\x16STATE_DIRECT_CONNECTED\x10\x04\x12\x10\n" +
	"\fSTATE_FAILED\x10\x05*\xe3\x02\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14EVENT_PEER_CONNECTED\x10\x01\x12\x1b\n" +
	"\x17EVENT_PEER_DISCONNECTED\x10\x02\x12'\n" +
	"#EVENT_CONNECTION_UPGRADED_TO_DIRECT\x10\x03\x12\x1b\n" +
	"\x17EVENT_HOLE_PUNCH_FAILED\x10\x04\x12\x1c\n" +
	"\x18EVENT_TRANSFER_REQUESTED\x10\x05\x12\x1a\n" +
	"\x16EVENT_TRANSFER_STARTED\x10\x06\x12\x1b\n" +
	"\x17EVENT_TRANSFER_PROGRESS\x10\a\x12\x1c\n" +
	"\x18EVENT_TRANSFER_COMPLETED\x10\b\x12\x19\n" +
	"\x15EVENT_TRANSFER_FAILED\x10\t\x12\x1c\n" +
	"\x18EVENT_TRANSFER_CANCELLED\x10\n" +
	"\x12\x18\n" +
	"\x14EVENT_FILE_REQUESTED\x10\v2\xe2\x05\n" +
	"\aP2PNode\x12F\n" +
	"\vGetNodeInfo\x12\x1a.p2p.v1.GetNodeInfoRequest\x1a\x1b.p2p.v1.GetNodeInfoResponse\x12:\n" +
	"\aConnect\x12\x16.p2p.v1.ConnectRequest\x1a\x17.p2p.v1.ConnectResponse\x12C\n" +
	"\n" +
	"Disconnect\x12\x19.p2p.v1.DisconnectRequest\x1a\x1a.p2p.v1.DisconnectResponse\x12^\n" +
	"\x13GetConnectionStatus\x12\".p2p.v1.GetConnectionStatusRequest\x1a#.p2p.v1.GetConnectionStatusResponse\x12>\n" +
	"\vWatchEvents\x12\x1a.p2p.v1.WatchEventsRequest\x1a\x11.p2p.v1.NodeEvent0\x01\x12<\n" +
	"\bSendFile\x12\x17.p2p.v1.SendFileRequest\x1a\x15.p2p.v1.TransferEvent0\x01\x12@\n" +
	"\n" +
	"AcceptFile\x12\x19.p2p.v1.AcceptFileRequest\x1a\x15.p2p.v1.TransferEvent0\x01\x12O\n" +
	"\x0eCancelTransfer\x12\x1d.p2p.v1.CancelTransferRequest\x1a\x1e.p2p.v1.CancelTransferResponse\x12U\n" +
	"\x11GetTransferStatus\x12 .p2p.v1.GetTransferStatusRequest\x1a\x1e.p2p.v1.TransferStatusResponse\x12F\n" +
	"\vRequestFile\x12\x1a.p2p.v1.RequestFileRequest\x1a\x1b.p2p.v1.RequestFileResponseB\x14Z\x12internal/api/p2pv1b\x06proto3"

var (
	file_p2p_proto_rawDescOnce sync.Once
	file_p2p_proto_rawDescData []byte
)

func file_p2p_proto_rawDescGZIP() []byte {
	file_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)))
	})
	return file_p2p_proto_rawDescData
}

var file_p2p_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_p2p_proto_goTypes = []any{
	(Reachability)(0),                   // 0: p2p.v1.Reachability
	(ConnectionState)(0),                // 1: p2p.v1.ConnectionState
	(EventType)(0),                      // 2: p2p.v1.EventType
	(*GetNodeInfoRequest)(nil),          // 3: p2p.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),         // 4: p2p.v1.GetNodeInfoResponse
	(*ConnectRequest)(nil),              // 5: p2p.v1.ConnectRequest
	(*ConnectResponse)(nil),             // 6: p2p.v1.ConnectResponse
	(*DisconnectRequest)(nil),           // 7: p2p.v1.DisconnectRequest
	(*DisconnectResponse)(nil),          // 8: p2p.v1.DisconnectResponse
	(*GetConnectionStatusRequest)(nil),  // 9: p2p.v1.GetConnectionStatusRequest
	(*GetConnectionStatusResponse)(nil), // 10: p2p.v1.GetConnectionStatusResponse
	(*WatchEventsRequest)(nil),          // 11: p2p.v1.WatchEventsRequest
	(*NodeEvent)(nil),                   // 12: p2p.v1.NodeEvent
	(*TransferMetadata)(nil),            // 13: p2p.v1.TransferMetadata
	(*SendFileRequest)(nil),             // 14: p2p.v1.SendFileRequest
	(*AcceptFileRequest)(nil),           // 15: p2p.v1.AcceptFileRequest
	(*TransferEvent)(nil),               // 16: p2p.v1.TransferEvent
	(*CancelTransferRequest)(nil),       // 17: p2p.v1.CancelTransferRequest
	(*CancelTransferResponse)(nil),      // 18: p2p.v1.CancelTransferResponse
	(*GetTransferStatusRequest)(nil),    // 19: p2p.v1.GetTransferStatusRequest
	(*TransferStatusResponse)(nil),      // 20: p2p.v1.TransferStatusResponse
	(*RequestFileRequest)(nil),          // 21: p2p.v1.RequestFileRequest
	(*RequestFileResponse)(nil),         // 22: p2p.v1.RequestFileResponse
}
var file_p2p_proto_depIdxs = []int32{
	0,  // 0: p2p.v1.GetNodeInfoResponse.reachability:type_name -> p2p.v1.Reachability
	1,  // 1: p2p.v1.ConnectResponse.state:type_name -> p2p.v1.ConnectionState
	1,  // 2: p2p.v1.GetConnectionStatusResponse.state:type_name -> p2p.v1.ConnectionState
	2,  // 3: p2p.v1.NodeEvent.type:type_name -> p2p.v1.EventType
	13, // 4: p2p.v1.NodeEvent.metadata:type_name -> p2p.v1.TransferMetadata
	2,  // 5: p2p.v1.TransferEvent.state:type_name -> p2p.v1.EventType
	2,  // 6: p2p.v1.TransferStatusResponse.state:type_name -> p2p.v1.EventType
	3,  // 7: p2p.v1.P2PNode.GetNodeInfo:input_type -> p2p.v1.GetNodeInfoRequest
	5,  // 8: p2p.v1.P2PNode.Connect:input_type -> p2p.v1.ConnectRequest
	7,  // 9: p2p.v1.P2PNode.Disconnect:input_type -> p2p.v1.DisconnectRequest
	9,  // 10: p2p.v1.P2PNode.GetConnectionStatus:input_type -> p2p.v1.GetConnectionStatusRequest
	11, // 11: p2p.v1.P2PNode.WatchEvents:input_type -> p2p.v1.WatchEventsRequest
	14, // 12: p2p.v1.P2PNode.SendFile:input_type -> p2p.v1.SendFileRequest
	15, // 13: p2p.v1.P2PNode.AcceptFile:input_type -> p2p.v1.AcceptFileRequest
	17, // 14: p2p.v1.P2PNode.CancelTransfer:input_type -> p2p.v1.CancelTransferRequest
	19, // 15: p2p.v1.P2PNode.GetTransferStatus:input_type -> p2p.v1.GetTransferStatusRequest
	21, // 16: p2p.v1.P2PNode.RequestFile:input_type -> p2p.v1.RequestFileRequest
	4,  // 17: p2p.v1.P2PNode.GetNodeInfo:output_type -> p2p.v1.GetNodeInfoResponse
	6,  // 18: p2p.v1.P2PNode.Connect:output_type -> p2p.v1.ConnectResponse
	8,  // 19: p2p.v1.P2PNode.Disconnect:output_type -> p2p.v1.DisconnectResponse
	10, // 20: p2p.v1.P2PNode.GetConnectionStatus:output_type -> p2p.v1.GetConnectionStatusResponse
	12, // 21: p2p.v1.P2PNode.WatchEvents:output_type -> p2p.v1.NodeEvent
	16, // 22: p2p.v1.P2PNode.SendFile:output_type -> p2p.v1.TransferEvent
	16, // 23: p2p.v1.P2PNode.AcceptFile:output_type -> p2p.v1.TransferEvent
	18, // 24: p2p.v1.P2PNode.CancelTransfer:output_type -> p2p.v1.CancelTransferResponse
	20, // 25: p2p.v1.P2PNode.GetTransferStatus:output_type -> p2p.v1.TransferStatusResponse
	22, // 26: p2p.v1.P2PNode.RequestFile:output_type -> p2p.v1.RequestFileResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_p2p_proto_init() }
func file_p2p_proto_init() {
	if File_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_rawDesc), len(file_p2p_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_proto_depIdxs,
		EnumInfos:         file_p2p_proto_enumTypes,
		MessageInfos:      file_p2p_proto_msgTypes,
	}.Build()
	File_p2p_proto = out.File
	file_p2p_proto_goTypes = nil
	file_p2p_proto_depIdxs = nil
}
