// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: p2p.proto

package p2pv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	P2PNode_GetNodeInfo_FullMethodName         = "/p2p.v1.P2PNode/GetNodeInfo"
	P2PNode_Connect_FullMethodName             = "/p2p.v1.P2PNode/Connect"
	P2PNode_Disconnect_FullMethodName          = "/p2p.v1.P2PNode/Disconnect"
	P2PNode_GetConnectionStatus_FullMethodName = "/p2p.v1.P2PNode/GetConnectionStatus"
	P2PNode_WatchEvents_FullMethodName         = "/p2p.v1.P2PNode/WatchEvents"
	P2PNode_SendFile_FullMethodName            = "/p2p.v1.P2PNode/SendFile"
	P2PNode_AcceptFile_FullMethodName          = "/p2p.v1.P2PNode/AcceptFile"
	P2PNode_CancelTransfer_FullMethodName      = "/p2p.v1.P2PNode/CancelTransfer"
	P2PNode_GetTransferStatus_FullMethodName   = "/p2p.v1.P2PNode/GetTransferStatus"
	P2PNode_RequestFile_FullMethodName         = "/p2p.v1.P2PNode/RequestFile"
	P2PNode_GetTrainingTask_FullMethodName     = "/p2p.v1.P2PNode/GetTrainingTask"
	P2PNode_GetModel_FullMethodName            = "/p2p.v1.P2PNode/GetModel"
	P2PNode_GetShard_FullMethodName            = "/p2p.v1.P2PNode/GetShard"
	P2PNode_SendUpdate_FullMethodName          = "/p2p.v1.P2PNode/SendUpdate"
	P2PNode_ServeClientRequests_FullMethodName = "/p2p.v1.P2PNode/ServeClientRequests"
)

// P2PNodeClient is the client API for P2PNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service implemented by the Go p2p-node standalone sidecar executable.
// Exposes a localhost-bound gRPC interface to Python applications.
type P2PNodeClient interface {
	// --- Node & Connection Management ---
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error)
	// --- Base File Transfer RPCs ---
	SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error)
	AcceptFile(ctx context.Context, in *AcceptFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error)
	CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error)
	GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	RequestFile(ctx context.Context, in *RequestFileRequest, opts ...grpc.CallOption) (*RequestFileResponse, error)
	// --- Trainer P2P High-Level Workflows ---
	// Step 1: Request training task specification from Client
	GetTrainingTask(ctx context.Context, in *GetTrainingTaskRequest, opts ...grpc.CallOption) (*GetTrainingTaskResponse, error)
	// Step 2: Request base model checkpoint from Client (streams over P2P, saves to working dir)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	// Step 3: Request assigned dataset shard from Client (streams over P2P, saves to working dir)
	GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error)
	// Step 4: Stream trained weights delta and metadata back to Client
	SendUpdate(ctx context.Context, in *SendUpdateRequest, opts ...grpc.CallOption) (*SendUpdateResponse, error)
	// --- Client Inbound Request Dispatch ---
	// Long-lived bidirectional stream for Client Python adapter to receive inbound
	// requests arriving over libp2p and return command handler execution outputs.
	ServeClientRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientActionResponse, ClientActionRequest], error)
}

type p2PNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewP2PNodeClient(cc grpc.ClientConnInterface) P2PNodeClient {
	return &p2PNodeClient{cc}
}

func (c *p2PNodeClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, P2PNode_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, P2PNode_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) GetConnectionStatus(ctx context.Context, in *GetConnectionStatusRequest, opts ...grpc.CallOption) (*GetConnectionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionStatusResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetConnectionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PNode_ServiceDesc.Streams[0], P2PNode_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, NodeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_WatchEventsClient = grpc.ServerStreamingClient[NodeEvent]

func (c *p2PNodeClient) SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PNode_ServiceDesc.Streams[1], P2PNode_SendFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendFileRequest, TransferEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_SendFileClient = grpc.ServerStreamingClient[TransferEvent]

func (c *p2PNodeClient) AcceptFile(ctx context.Context, in *AcceptFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PNode_ServiceDesc.Streams[2], P2PNode_AcceptFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AcceptFileRequest, TransferEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_AcceptFileClient = grpc.ServerStreamingClient[TransferEvent]

func (c *p2PNodeClient) CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransferResponse)
	err := c.cc.Invoke(ctx, P2PNode_CancelTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) RequestFile(ctx context.Context, in *RequestFileRequest, opts ...grpc.CallOption) (*RequestFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestFileResponse)
	err := c.cc.Invoke(ctx, P2PNode_RequestFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) GetTrainingTask(ctx context.Context, in *GetTrainingTaskRequest, opts ...grpc.CallOption) (*GetTrainingTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrainingTaskResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetTrainingTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) GetShard(ctx context.Context, in *GetShardRequest, opts ...grpc.CallOption) (*GetShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardResponse)
	err := c.cc.Invoke(ctx, P2PNode_GetShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) SendUpdate(ctx context.Context, in *SendUpdateRequest, opts ...grpc.CallOption) (*SendUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendUpdateResponse)
	err := c.cc.Invoke(ctx, P2PNode_SendUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *p2PNodeClient) ServeClientRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientActionResponse, ClientActionRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &P2PNode_ServiceDesc.Streams[3], P2PNode_ServeClientRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientActionResponse, ClientActionRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_ServeClientRequestsClient = grpc.BidiStreamingClient[ClientActionResponse, ClientActionRequest]

// P2PNodeServer is the server API for P2PNode service.
// All implementations must embed UnimplementedP2PNodeServer
// for forward compatibility.
//
// Service implemented by the Go p2p-node standalone sidecar executable.
// Exposes a localhost-bound gRPC interface to Python applications.
type P2PNodeServer interface {
	// --- Node & Connection Management ---
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[NodeEvent]) error
	// --- Base File Transfer RPCs ---
	SendFile(*SendFileRequest, grpc.ServerStreamingServer[TransferEvent]) error
	AcceptFile(*AcceptFileRequest, grpc.ServerStreamingServer[TransferEvent]) error
	CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error)
	GetTransferStatus(context.Context, *GetTransferStatusRequest) (*TransferStatusResponse, error)
	RequestFile(context.Context, *RequestFileRequest) (*RequestFileResponse, error)
	// --- Trainer P2P High-Level Workflows ---
	// Step 1: Request training task specification from Client
	GetTrainingTask(context.Context, *GetTrainingTaskRequest) (*GetTrainingTaskResponse, error)
	// Step 2: Request base model checkpoint from Client (streams over P2P, saves to working dir)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	// Step 3: Request assigned dataset shard from Client (streams over P2P, saves to working dir)
	GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error)
	// Step 4: Stream trained weights delta and metadata back to Client
	SendUpdate(context.Context, *SendUpdateRequest) (*SendUpdateResponse, error)
	// --- Client Inbound Request Dispatch ---
	// Long-lived bidirectional stream for Client Python adapter to receive inbound
	// requests arriving over libp2p and return command handler execution outputs.
	ServeClientRequests(grpc.BidiStreamingServer[ClientActionResponse, ClientActionRequest]) error
	mustEmbedUnimplementedP2PNodeServer()
}

// UnimplementedP2PNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedP2PNodeServer struct{}

func (UnimplementedP2PNodeServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedP2PNodeServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedP2PNodeServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedP2PNodeServer) GetConnectionStatus(context.Context, *GetConnectionStatusRequest) (*GetConnectionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionStatus not implemented")
}
func (UnimplementedP2PNodeServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[NodeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedP2PNodeServer) SendFile(*SendFileRequest, grpc.ServerStreamingServer[TransferEvent]) error {
	return status.Error(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedP2PNodeServer) AcceptFile(*AcceptFileRequest, grpc.ServerStreamingServer[TransferEvent]) error {
	return status.Error(codes.Unimplemented, "method AcceptFile not implemented")
}
func (UnimplementedP2PNodeServer) CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransfer not implemented")
}
func (UnimplementedP2PNodeServer) GetTransferStatus(context.Context, *GetTransferStatusRequest) (*TransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedP2PNodeServer) RequestFile(context.Context, *RequestFileRequest) (*RequestFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFile not implemented")
}
func (UnimplementedP2PNodeServer) GetTrainingTask(context.Context, *GetTrainingTaskRequest) (*GetTrainingTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrainingTask not implemented")
}
func (UnimplementedP2PNodeServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedP2PNodeServer) GetShard(context.Context, *GetShardRequest) (*GetShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShard not implemented")
}
func (UnimplementedP2PNodeServer) SendUpdate(context.Context, *SendUpdateRequest) (*SendUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendUpdate not implemented")
}
func (UnimplementedP2PNodeServer) ServeClientRequests(grpc.BidiStreamingServer[ClientActionResponse, ClientActionRequest]) error {
	return status.Error(codes.Unimplemented, "method ServeClientRequests not implemented")
}
func (UnimplementedP2PNodeServer) mustEmbedUnimplementedP2PNodeServer() {}
func (UnimplementedP2PNodeServer) testEmbeddedByValue()                 {}

// UnsafeP2PNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to P2PNodeServer will
// result in compilation errors.
type UnsafeP2PNodeServer interface {
	mustEmbedUnimplementedP2PNodeServer()
}

func RegisterP2PNodeServer(s grpc.ServiceRegistrar, srv P2PNodeServer) {
	// If the following call panics, it indicates UnimplementedP2PNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&P2PNode_ServiceDesc, srv)
}

func _P2PNode_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_GetConnectionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetConnectionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetConnectionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetConnectionStatus(ctx, req.(*GetConnectionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PNodeServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, NodeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_WatchEventsServer = grpc.ServerStreamingServer[NodeEvent]

func _P2PNode_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PNodeServer).SendFile(m, &grpc.GenericServerStream[SendFileRequest, TransferEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_SendFileServer = grpc.ServerStreamingServer[TransferEvent]

func _P2PNode_AcceptFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AcceptFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(P2PNodeServer).AcceptFile(m, &grpc.GenericServerStream[AcceptFileRequest, TransferEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_AcceptFileServer = grpc.ServerStreamingServer[TransferEvent]

func _P2PNode_CancelTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).CancelTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_CancelTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).CancelTransfer(ctx, req.(*CancelTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetTransferStatus(ctx, req.(*GetTransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_RequestFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).RequestFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_RequestFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).RequestFile(ctx, req.(*RequestFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_GetTrainingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainingTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetTrainingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetTrainingTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetTrainingTask(ctx, req.(*GetTrainingTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_GetShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).GetShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_GetShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).GetShard(ctx, req.(*GetShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_SendUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(P2PNodeServer).SendUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: P2PNode_SendUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(P2PNodeServer).SendUpdate(ctx, req.(*SendUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _P2PNode_ServeClientRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(P2PNodeServer).ServeClientRequests(&grpc.GenericServerStream[ClientActionResponse, ClientActionRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type P2PNode_ServeClientRequestsServer = grpc.BidiStreamingServer[ClientActionResponse, ClientActionRequest]

// P2PNode_ServiceDesc is the grpc.ServiceDesc for P2PNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var P2PNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.v1.P2PNode",
	HandlerType: (*P2PNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _P2PNode_GetNodeInfo_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _P2PNode_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _P2PNode_Disconnect_Handler,
		},
		{
			MethodName: "GetConnectionStatus",
			Handler:    _P2PNode_GetConnectionStatus_Handler,
		},
		{
			MethodName: "CancelTransfer",
			Handler:    _P2PNode_CancelTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _P2PNode_GetTransferStatus_Handler,
		},
		{
			MethodName: "RequestFile",
			Handler:    _P2PNode_RequestFile_Handler,
		},
		{
			MethodName: "GetTrainingTask",
			Handler:    _P2PNode_GetTrainingTask_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _P2PNode_GetModel_Handler,
		},
		{
			MethodName: "GetShard",
			Handler:    _P2PNode_GetShard_Handler,
		},
		{
			MethodName: "SendUpdate",
			Handler:    _P2PNode_SendUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _P2PNode_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendFile",
			Handler:       _P2PNode_SendFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AcceptFile",
			Handler:       _P2PNode_AcceptFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServeClientRequests",
			Handler:       _P2PNode_ServeClientRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "p2p.proto",
}
