# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import p2p_pb2 as p2p__pb2
except ImportError:
    import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class P2PNodeStub:
    """Service implemented by the Go p2p-node standalone sidecar executable.
    Exposes a localhost-bound gRPC interface to Python applications.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/p2p.v1.P2PNode/GetNodeInfo',
                request_serializer=p2p__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=p2p__pb2.GetNodeInfoResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/p2p.v1.P2PNode/Connect',
                request_serializer=p2p__pb2.ConnectRequest.SerializeToString,
                response_deserializer=p2p__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/p2p.v1.P2PNode/Disconnect',
                request_serializer=p2p__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=p2p__pb2.DisconnectResponse.FromString,
                _registered_method=True)
        self.GetConnectionStatus = channel.unary_unary(
                '/p2p.v1.P2PNode/GetConnectionStatus',
                request_serializer=p2p__pb2.GetConnectionStatusRequest.SerializeToString,
                response_deserializer=p2p__pb2.GetConnectionStatusResponse.FromString,
                _registered_method=True)
        self.WatchEvents = channel.unary_stream(
                '/p2p.v1.P2PNode/WatchEvents',
                request_serializer=p2p__pb2.WatchEventsRequest.SerializeToString,
                response_deserializer=p2p__pb2.NodeEvent.FromString,
                _registered_method=True)
        self.SendFile = channel.unary_stream(
                '/p2p.v1.P2PNode/SendFile',
                request_serializer=p2p__pb2.SendFileRequest.SerializeToString,
                response_deserializer=p2p__pb2.TransferEvent.FromString,
                _registered_method=True)
        self.AcceptFile = channel.unary_stream(
                '/p2p.v1.P2PNode/AcceptFile',
                request_serializer=p2p__pb2.AcceptFileRequest.SerializeToString,
                response_deserializer=p2p__pb2.TransferEvent.FromString,
                _registered_method=True)
        self.CancelTransfer = channel.unary_unary(
                '/p2p.v1.P2PNode/CancelTransfer',
                request_serializer=p2p__pb2.CancelTransferRequest.SerializeToString,
                response_deserializer=p2p__pb2.CancelTransferResponse.FromString,
                _registered_method=True)
        self.GetTransferStatus = channel.unary_unary(
                '/p2p.v1.P2PNode/GetTransferStatus',
                request_serializer=p2p__pb2.GetTransferStatusRequest.SerializeToString,
                response_deserializer=p2p__pb2.TransferStatusResponse.FromString,
                _registered_method=True)
        self.RequestFile = channel.unary_unary(
                '/p2p.v1.P2PNode/RequestFile',
                request_serializer=p2p__pb2.RequestFileRequest.SerializeToString,
                response_deserializer=p2p__pb2.RequestFileResponse.FromString,
                _registered_method=True)
        self.GetTrainingTask = channel.unary_unary(
                '/p2p.v1.P2PNode/GetTrainingTask',
                request_serializer=p2p__pb2.GetTrainingTaskRequest.SerializeToString,
                response_deserializer=p2p__pb2.GetTrainingTaskResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/p2p.v1.P2PNode/GetModel',
                request_serializer=p2p__pb2.GetModelRequest.SerializeToString,
                response_deserializer=p2p__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.GetShard = channel.unary_unary(
                '/p2p.v1.P2PNode/GetShard',
                request_serializer=p2p__pb2.GetShardRequest.SerializeToString,
                response_deserializer=p2p__pb2.GetShardResponse.FromString,
                _registered_method=True)
        self.SendUpdate = channel.unary_unary(
                '/p2p.v1.P2PNode/SendUpdate',
                request_serializer=p2p__pb2.SendUpdateRequest.SerializeToString,
                response_deserializer=p2p__pb2.SendUpdateResponse.FromString,
                _registered_method=True)
        self.ServeClientRequests = channel.stream_stream(
                '/p2p.v1.P2PNode/ServeClientRequests',
                request_serializer=p2p__pb2.ClientActionResponse.SerializeToString,
                response_deserializer=p2p__pb2.ClientActionRequest.FromString,
                _registered_method=True)


class P2PNodeServicer:
    """Service implemented by the Go p2p-node standalone sidecar executable.
    Exposes a localhost-bound gRPC interface to Python applications.
    """

    def GetNodeInfo(self, request, context):
        """--- Node & Connection Management ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFile(self, request, context):
        """--- Base File Transfer RPCs ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransferStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingTask(self, request, context):
        """--- Trainer P2P High-Level Workflows ---
        Step 1: Request training task specification from Client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Step 2: Request base model checkpoint from Client (streams over P2P, saves to working dir)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShard(self, request, context):
        """Step 3: Request assigned dataset shard from Client (streams over P2P, saves to working dir)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendUpdate(self, request, context):
        """Step 4: Stream trained weights delta and metadata back to Client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeClientRequests(self, request_iterator, context):
        """--- Client Inbound Request Dispatch ---
        Long-lived bidirectional stream for Client Python adapter to receive inbound
        requests arriving over libp2p and return command handler execution outputs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=p2p__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=p2p__pb2.GetNodeInfoResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=p2p__pb2.ConnectRequest.FromString,
                    response_serializer=p2p__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=p2p__pb2.DisconnectRequest.FromString,
                    response_serializer=p2p__pb2.DisconnectResponse.SerializeToString,
            ),
            'GetConnectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectionStatus,
                    request_deserializer=p2p__pb2.GetConnectionStatusRequest.FromString,
                    response_serializer=p2p__pb2.GetConnectionStatusResponse.SerializeToString,
            ),
            'WatchEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchEvents,
                    request_deserializer=p2p__pb2.WatchEventsRequest.FromString,
                    response_serializer=p2p__pb2.NodeEvent.SerializeToString,
            ),
            'SendFile': grpc.unary_stream_rpc_method_handler(
                    servicer.SendFile,
                    request_deserializer=p2p__pb2.SendFileRequest.FromString,
                    response_serializer=p2p__pb2.TransferEvent.SerializeToString,
            ),
            'AcceptFile': grpc.unary_stream_rpc_method_handler(
                    servicer.AcceptFile,
                    request_deserializer=p2p__pb2.AcceptFileRequest.FromString,
                    response_serializer=p2p__pb2.TransferEvent.SerializeToString,
            ),
            'CancelTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTransfer,
                    request_deserializer=p2p__pb2.CancelTransferRequest.FromString,
                    response_serializer=p2p__pb2.CancelTransferResponse.SerializeToString,
            ),
            'GetTransferStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransferStatus,
                    request_deserializer=p2p__pb2.GetTransferStatusRequest.FromString,
                    response_serializer=p2p__pb2.TransferStatusResponse.SerializeToString,
            ),
            'RequestFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFile,
                    request_deserializer=p2p__pb2.RequestFileRequest.FromString,
                    response_serializer=p2p__pb2.RequestFileResponse.SerializeToString,
            ),
            'GetTrainingTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingTask,
                    request_deserializer=p2p__pb2.GetTrainingTaskRequest.FromString,
                    response_serializer=p2p__pb2.GetTrainingTaskResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=p2p__pb2.GetModelRequest.FromString,
                    response_serializer=p2p__pb2.GetModelResponse.SerializeToString,
            ),
            'GetShard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShard,
                    request_deserializer=p2p__pb2.GetShardRequest.FromString,
                    response_serializer=p2p__pb2.GetShardResponse.SerializeToString,
            ),
            'SendUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUpdate,
                    request_deserializer=p2p__pb2.SendUpdateRequest.FromString,
                    response_serializer=p2p__pb2.SendUpdateResponse.SerializeToString,
            ),
            'ServeClientRequests': grpc.stream_stream_rpc_method_handler(
                    servicer.ServeClientRequests,
                    request_deserializer=p2p__pb2.ClientActionResponse.FromString,
                    response_serializer=p2p__pb2.ClientActionRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2p.v1.P2PNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p2p.v1.P2PNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2PNode:
    """Service implemented by the Go p2p-node standalone sidecar executable.
    Exposes a localhost-bound gRPC interface to Python applications.
    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetNodeInfo',
            p2p__pb2.GetNodeInfoRequest.SerializeToString,
            p2p__pb2.GetNodeInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/Connect',
            p2p__pb2.ConnectRequest.SerializeToString,
            p2p__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/Disconnect',
            p2p__pb2.DisconnectRequest.SerializeToString,
            p2p__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetConnectionStatus',
            p2p__pb2.GetConnectionStatusRequest.SerializeToString,
            p2p__pb2.GetConnectionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/p2p.v1.P2PNode/WatchEvents',
            p2p__pb2.WatchEventsRequest.SerializeToString,
            p2p__pb2.NodeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/p2p.v1.P2PNode/SendFile',
            p2p__pb2.SendFileRequest.SerializeToString,
            p2p__pb2.TransferEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/p2p.v1.P2PNode/AcceptFile',
            p2p__pb2.AcceptFileRequest.SerializeToString,
            p2p__pb2.TransferEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/CancelTransfer',
            p2p__pb2.CancelTransferRequest.SerializeToString,
            p2p__pb2.CancelTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransferStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetTransferStatus',
            p2p__pb2.GetTransferStatusRequest.SerializeToString,
            p2p__pb2.TransferStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/RequestFile',
            p2p__pb2.RequestFileRequest.SerializeToString,
            p2p__pb2.RequestFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetTrainingTask',
            p2p__pb2.GetTrainingTaskRequest.SerializeToString,
            p2p__pb2.GetTrainingTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetModel',
            p2p__pb2.GetModelRequest.SerializeToString,
            p2p__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/GetShard',
            p2p__pb2.GetShardRequest.SerializeToString,
            p2p__pb2.GetShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2p.v1.P2PNode/SendUpdate',
            p2p__pb2.SendUpdateRequest.SerializeToString,
            p2p__pb2.SendUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServeClientRequests(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/p2p.v1.P2PNode/ServeClientRequests',
            p2p__pb2.ClientActionResponse.SerializeToString,
            p2p__pb2.ClientActionRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
