// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainSwarm.Coordinator.Infrastructure.Persistence;

#nullable disable

namespace TrainSwarm.Coordinator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CoordinatorDbContext))]
    partial class CoordinatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrainSwarm.Coordinator.Domain.Entities.TrainingTask", b =>
                {
                    b.Property<Guid>("TrainingTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainerNodeId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("TrainingTaskId");

                    b.ToTable("TrainingTasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
