# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator_commands.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'coordinator_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63oordinator_commands.proto\x12\x16trainswarm.coordinator\"0\n\x1aTrainerRegistrationRequest\x12\x12\n\ntrainer_id\x18\x01 \x01(\t\"9\n\x0f\x43ommandEnvelope\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x8f\x01\n\x19\x43oordinatorCommandService\x12r\n\x11SubscribeCommands\x12\x32.trainswarm.coordinator.TrainerRegistrationRequest\x1a\'.trainswarm.coordinator.CommandEnvelope0\x01\x42\x1e\xaa\x02\x1bTrainSwarm.Coordinator.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033TrainSwarm.Coordinator.Grpc'
  _globals['_TRAINERREGISTRATIONREQUEST']._serialized_start=54
  _globals['_TRAINERREGISTRATIONREQUEST']._serialized_end=102
  _globals['_COMMANDENVELOPE']._serialized_start=104
  _globals['_COMMANDENVELOPE']._serialized_end=161
  _globals['_COORDINATORCOMMANDSERVICE']._serialized_start=164
  _globals['_COORDINATORCOMMANDSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
